version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    environment:
      POSTGRES_USER: hiral
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: resume_finder
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    tty: true

volumes:
  pgvector-data:
  ollama-data: