version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-travel-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: travel_blog
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
